import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import GridLayout from "@/components/layout/GridLayout";
import { Toaster } from "sonner";
import CheckActiveSession from "@/components/roleCheckers/CheckActiveSession";

const montserrat = Montserrat({
  subsets: ["latin"],
  adjustFontFallback: false,
  display: "swap",
});

export const metadata: Metadata = {
  title: "Edugami AR",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} text-light`}>
        <CheckActiveSession />
        <Toaster />
        <GridLayout>{children}</GridLayout>
      </body>
    </html>
  );
}
